sudo: required
services:
  - docker

before_install:
  - docker build -t fakhrulfaizdev/docker-react -f Dockerfile.dev .

script:
  - docker run fakhrulfaizdev/docker-react npm run test -- --coverage --watchAll=false
